# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fa408ab96203ebe12697d9a1c150c6f2ad6ad2150aacaaaae1bead0f5168323312ddf783832f562d071e6c985cf9f9f889d0d8f75a967c3805aa8661b3e48f3

test:
  secret_key_base: 475caef8344a5d12351cf5dda194d756964852bcf38a47306b90d53ca7df6ff9616e44a32eac000a5d14ac3cf88083ff11a8f07aece769de0a859b7287847a11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
